### ISSUE TITLE
Mac使用积累

### ISSUE THREAD

**Issue by i-am-annewang** [i-am-annewang/wanghuiying.github.io#34]
### mac 使用总结
+ control + space -- 切换中英文输入法
+ command + space -- 调出 spotlight 快速查找文件，应用，网页
+ command + q -- 彻底结束应用程序
+ control + c -- 结束终端
+ control + 鼠标点击 -- 鼠标右键
+ 左键长按应用，弹出框，选择选项，固定在dock栏
+ 清理屏幕 clear
+ install mysql in mac: `brew install mysql`.
+ login in mysql without enter a password:`mysql -uroot`;
+ create database in mysql: `create database if not exist asics3`;
+ `cd go/src/github.com/theplant/aigle/aigleapp`
+ 快速回到根目录/Usr/apple --`cd ~ `
+ tab键快速补齐
+ 常用工作目录
`cd go/src/github.com/theplant/`
+ vscode 安装命令行插件`code`, 进入目录之后，直接输入`code .` 在vscode打开当前目录
+ `pwd`显示当前文件目录，编辑zsh环境变量 zshrc文件
```
`vi ~/.zshrc`

**Comment by WangHuiying** [comment]
Dash来使用本地的API
![image](https://user-images.githubusercontent.com/18532655/32312671-f474e89e-bfd9-11e7-9148-7f88fbfd0396.png)

**Comment by WangHuiying** [comment]
https://segmentfault.com/a/1190000010748343
```
对于 GUI 软件，需要使用 brew cask 插件安装
安装 brew cask 插件。

brew install caskroom/cask/brew-cask

# 开发工具
brew install git  # 版本控制软件
brew install node # 基于 js 的服务端引擎

# gui 工具
brew cask install phpstorm   # 编辑器
brew cask install sublime-text   # 编辑器
brew cask install google-chrome # google 浏览器
brew cask install p4merge # git 冲突解决工具
brew cask install the-unarchiver # 解压工具
brew cask install cheatsheet # 显示 mac 下快捷键
brew cask install ichm # 阅读 chm 文件
brew cask install iterm2 # 终端工具
brew cask install Cyberduck # 连接 sftp 工具
brew cask install licecap # gif 制作工具    
brew cask install spectacle # 控制屏幕工具
```

**Comment by WangHuiying** [comment]
让电脑说话`say hello`
