### ISSUE TITLE
想法

### ISSUE THREAD

**Issue by i-am-annewang** [i-am-annewang/wanghuiying.github.io#36]
1. 公交车可以自动根据人流量规划出行时间，避免空车浪费

**Comment by WangHuiying** [comment]
PPT模板
http://www.ypppt.com/moban/jianyue/

**Comment by WangHuiying** [comment]
1. 为什么要使用电子商务 B2C
2. 为什么要拥有自己开发的网站而不直接在第三方网站上
3. 为什么要开发基于用户行为分析的推荐的功能

**Comment by WangHuiying** [comment]
npm xmas
![image](https://user-images.githubusercontent.com/18532655/34333727-b3344378-e97a-11e7-92d4-2a122879f84e.png)
