### ISSUE TITLE
平常在网上找到的好东西

### ISSUE THREAD

**Issue by i-am-annewang** [i-am-annewang/wanghuiying.github.io#8]
#1. github在线简历
```
http://hacknical.com/github/WangHuiying?locale=zh
```

Vue.js 创新项目
[create-a-github-file-explorer-using-vue-js](https://scotch.io/tutorials/create-a-github-file-explorer-using-vue-js)

[Vue 2.0 右键菜单组件](https://github.com/xunleif2e/vue-context-menu)
![image](https://user-images.githubusercontent.com/18532655/28863546-ec723c90-779b-11e7-9d22-385f6c7549d7.png)

**Comment by WangHuiying** [comment]
http://cssreference.io/property/align-items/
赏心悦目的CSS学习网站

**Comment by WangHuiying** [comment]
在线编写文档，今天看到很多文档是由日本人写的，中文的文档并不多，而且存在一个现象是写文档的人水平比较低，虽然有开源精神，但是难免词不达意。而技术真的过硬的，一般都是直接看英文文档，或者编写代码，鲜少有人翻译文章。
对于我而言，目前还是一个小白，所以努力着让自己变得更加强大吧。
https://docsify.js.org/#/
这个网站是一个在线编写文档的网站，网站色调和vue很像，很喜欢这个萌萌的画风。

**Comment by WangHuiying** [comment]
AI 插画http://make.girls.moe/#/、
https://github.com/makegirlsmoe
![default](https://user-images.githubusercontent.com/18532655/29354742-f8f753a0-82a0-11e7-9b68-5a960e818f3a.png)
![image](https://user-images.githubusercontent.com/18532655/29354767-1092f0aa-82a1-11e7-95f0-7b6abb8b5318.png)

**Comment by WangHuiying** [comment]
[gtop](https://github.com/aksakalli/gtop)
用命令行监听资源使用情况
![](https://raw.githubusercontent.com/aksakalli/gtop/master/img/demo.gif)

**Comment by WangHuiying** [comment]
![image](https://user-images.githubusercontent.com/18532655/29397937-1df6691c-8354-11e7-82f9-403177353e72.png)
http://www.bootcss.com/p/buttons/
```
<button class="button button-large button-plain button-border button-circle"><i class="fa fa-reply"></i></button>
<button class="button button-large button-plain button-border button-box"><i class="fa fa-star"></i></button>
<button class="button button-large button-plain button-border button-square"><i class="fa fa-trash-o"></i></button>
```
  <button class="button button-large button-plain button-borderless"><i class="fa fa-tag"></i></button>

**Comment by WangHuiying** [comment]
web 安全色
http://www.bootcss.com/p/buttons/  
![image](https://user-images.githubusercontent.com/18532655/29398000-75b53520-8354-11e7-9c58-87d264137da3.png)

**Comment by WangHuiying** [comment]
之前[you-get](https://github.com/soimort/you-get) star14.7k 可以下载音乐视频，今天又发现一个[youtube-dl](https://github.com/rg3/youtube-dl)star 5.4k, l两个工具都是python开发的
一个是直接`you-get http://music.163.com/#/song?id=499274178`
另一个是 `youtube-del 'http://music.163.com/#/song?id=499274178'`

**Comment by WangHuiying** [comment]
ubuntu下安装pip
http://blog.csdn.net/u013647382/article/details/51694954
```
两种方法，直接安装 pip， 或者先安装 easy-install，在用 easy-install 安装 pip：

方法一：直接安装
第一行安装， 第二行更新
$ sudo apt-get install python-pip python-dev build-essential 
$ sudo pip install --upgrade pip 

方法二：用 easy-install 安装 pip
Install pip
$ sudo apt-get install python-setuptools python-dev build-essential 
Install pip’
$ sudo easy_install pip 
Install virtualenv
$ sudo pip install --upgrade virtualenv 
```

**Comment by WangHuiying** [comment]
http://www.inskeeper.com/
![image](https://user-images.githubusercontent.com/18532655/29647046-875eed24-88b9-11e7-9620-ee3c2acbdcf0.png)

**Comment by WangHuiying** [comment]
http://bird.so/search?q=hover%20img

<img width="903" alt="screen shot 2017-10-27 at 10 22 45 am" src="https://user-images.githubusercontent.com/18532655/32085348-fd4a4b18-bb00-11e7-8c61-a0fddef1b0b9.png">

超级棒的一个搜索引擎，专门为程序员设计，搜索的结果可以直接给你一个高票的答案呢，可以代替百度

**Comment by WangHuiying** [comment]
W3C School 全新改版，还加入了当前流行的grid
https://www.w3schools.com/howto/howto_css_image_overlay.asp

**Comment by WangHuiying** [comment]
好看的颜色
![image](https://user-images.githubusercontent.com/18532655/32085505-0c378630-bb02-11e7-96da-3448b6f2519b.png)

**Comment by WangHuiying** [comment]
比bootstrap更好用的组件 https://bulma.io/documentation/overview/start/
作者也是cssreference.io的作者

**Comment by WangHuiying** [comment]
比bootstrap更好用的前端框架
https://bulma.io/documentation/overview/start/，
作者是cssreference.io的作者
![image](https://user-images.githubusercontent.com/18532655/32308607-bbe94370-bfc1-11e7-9b2e-58706c41324a.png)

**Comment by WangHuiying** [comment]
http://bird.so/search?q=%20linux%20install%20yarn
